server.port: 8080
spring.data.mongodb.host: db
spring.data.mongodb.database: mmaps
spring.jackson.serialization.indent-output: true

---

spring.profiles: dev

spring.data.mongodb.host: localhost

logging.level.org.springframework.data.mongodb.core.MongoTemplate: DEBUG